name: Deploy to EC2 machine
on:
  push:
    branches:
      - main
      - dev
      - prod
  pull_request:
    branches:
      - main
jobs:
  build: # user-defined job name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code base
        uses: actions/checkout@v4
      - name: Copy code to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSHKEY }}
          port: 22
          source: ./ # Copy the code from the repository
          target: /home/ubuntu/ # Target directory on EC2 instance
      - name: Move code to /var/www/html with sudo
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSHKEY }}
          port: 22
          script: |
            sudo mv /home/ubuntu/index.html /var/www/html/
            sudo systemctl restart nginx
            
